[mgr]
prepend_keymap = [
    { on = [ "g", "r" ], run = "cd /", desc = "cd to /" },
    { on = [ "g", "d", "d" ], run = "cd ~/dev", desc = "cd to ~/dev" },
    { on = [ "g", "d", "n" ], run = "cd ~/dev-not-mine", desc = "cd to ~/dev-not-mine" },
    { on = [ "g", "o" ], run = "cd ~/documents", desc = "cd to ~/documents" },
    { on = [ "g", "D" ], run = "cd ~/downloads", desc = "cd to ~/downloads" },
    { on = [ "g", "p" ], run = "cd ~/pictures", desc = "cd to ~/pictures" },

    # For windows drive
    { on = [ "g", "w", "r" ], run = "cd /mnt/windows/", desc = "cd to Windows drive root" },
    { on = [ "g", "w", "h" ], run = "cd /mnt/windows/Users/almostblue/", desc = "cd to Windows drive home" },
    { on = [ "g", "w", "d", "d" ], run = "cd /mnt/windows/Users/almostblue/dev/", desc = "cd to Windows drive dev" },
    { on = [ "g", "w", "o" ], run = "cd /mnt/windows/Users/almostblue/Documents/", desc = "cd to Windows drive documents" },
    { on = [ "g", "w", "D" ], run = "cd /mnt/windows/Users/almostblue/Downloads/", desc = "cd to Windows drive downloads" },
    { on = [ "g", "w", "p" ], run = "cd /mnt/windows/Users/almostblue/Pictures/", desc = "cd to Windows drive pictures" },
    { on = [ "g", "w", "l" ], run = "cd /mnt/windows/Users/almostblue/AppData/Local/", desc = "cd to windows drive local appdata" },
    { on = [ "g", "w", "c" ], run = "cd /mnt/windows/Users/almostblue/AppData/Roaming/", desc = "cd to windows drive appdata roaming" },

    # For bootable SSD
    { on = [ "g", "s", "r" ], run = "cd /mnt/ssd/", desc = "cd to /mnt/ssd/" },
    { on = [ "g", "s", "r" ], run = "cd /mnt/ssd/home/almostblue/", desc = "cd to /mnt/ssd/home/almostblue/" },
    { on = [ "g", "s", "d", "d" ], run = "cd /mnt/ssd/home/almostblue/dev", desc = "cd to /mnt/ssd/home/almostblue/dev" },
    { on = [ "g", "s", "d", "n" ], run = "cd /mnt/ssd/home/almostblue/dev-not-mine", desc = "cd to /mnt/ssd/home/almostblue/dev-not-mine" },
    { on = [ "g", "s", "o" ], run = "cd /mnt/ssd/home/almostblue/documents", desc = "cd to /mnt/ssd/home/almostblue/documents" },
    { on = [ "g", "s", "D" ], run = "cd /mnt/ssd/home/almostblue/downloads", desc = "cd to /mnt/ssd/home/almostblue/downloads" },
    { on = [ "g", "s", "p" ], run = "cd /mnt/ssd/home/almostblue/pictures", desc = "cd to /mnt/ssd/home/almostblue/pictures" },

    { on = "<Enter>", run = "plugin smart-enter", desc = "Enter the child directory, or open the file" },
    { on = "o", run = "plugin smart-enter", desc = "Enter the child directory, or open the file" },
    { on = "F", run = "filter --smart", desc = "Filter files" },
    { on = "f", run = "cd --interactive", desc = "Go to a directory interactively" },
]

[input]
prepend_keymap = [
    { on = "<Esc>", run = "close", desc = "Cancel input" },
]
